### ISSUE TITLE
[ENHANCEMENT] Improvemente Readme - Following main readme leads into mongo container issues

### ISSUE THREAD

**Issue by entalpia** [Alien-Worlds/alienworlds-api#52]
### Type

Documentation Enhancement

### What is the motivation behind this improvement?

Following the guidelines included into the readme, apparently leads to issue on mongo db container set up

docker-compose build
docker-compose run api yarn
docker-compose run api yarn build
docker-compose run api yarn abis
docker-compose run api yarn mongo-indexes <-- **here**
docker-compose run api yarn husky

Docker compose stops with error and docker container **alienworlds-api_db_1** continues restarting

```
Failed to connect
 MongoServerSelectionError: getaddrinfo EAI_AGAIN db
    at Timeout._onTimeout (/var/www/api/node_modules/mongodb/lib/core/sdam/topology.js:438:30)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:510:7) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) { 'db:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

MongoServerSelectionError: getaddrinfo EAI_AGAIN db
    at Timeout._onTimeout (/var/www/api/node_modules/mongodb/lib/core/sdam/topology.js:438:30)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:510:7) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) {
      'db:27017' => ServerDescription {
        address: 'db:27017',
        error: Error: getaddrinfo EAI_AGAIN db
            at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:72:26) {
          name: 'MongoNetworkError'
        },
        roundTripTime: -1,
        lastUpdateTime: 595462,
        lastWriteDate: null,
        opTime: null,
        type: 'Unknown',
        topologyVersion: undefined,
        minWireVersion: 0,
        maxWireVersion: 0,
        hosts: [],
        passives: [],
        arbiters: [],
        tags: []
      }
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
```

### Describe your Improvement

Include a better description on how run the proper docker compose process and or edits configurations files.

**Comment by entalpia** [comment]
@ktamas77 did you had the chance to replicate this issue? thank you.

**Comment by buldo87** [comment]
I have the same problem how to solve it ?
